# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Yoda\UserBundle\Entity\User: bcrypt
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    
    role_hierarchy:
        ROLE_USER:           ROLE_USER 
        ROLE_ADMIN:          ROLE_ADMIN 
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    providers:
        our_database_users:
            entity: { class: UserBundle:User}
#        in_memory:
#            memory: 
#                users:
#                    user:   
#                        password: user
#                        roles:  'ROLE_USER' 
#                        
#                    admin:  
#                        password: admin
#                        roles : 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate
            form_login:
                login_path: login
                check_path: login
                
            logout:
                path:   logout
                target: /login
                

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

#            form_login: ~
#                http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: event, role: [ ROLE_USER, ROLE_ADMIN]  }
#        - { path: ^/delete, role: ROLE_ADMIN }